version: 2
jobs:
  build:
    working_directory: ~/firebase-auth-api
    docker:
      - image: circleci/ruby:2.5.0
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          RAILS_ENV: test
      - image: postgres:9.6
        environment:
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          POSTGRES_USER: ubuntu
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: Create DB
          command: bundle exec rake db:create

      - run:
          name: Migrate DB
          command: bundle exec rake db:migrate

      - run:
          name: chmod +x ./linter.sh
          command: chmod +x ./linter.sh

      - run:
          name: ./linter.sh
          command: ./linter.sh

      - run:
          name: Run rspec
          command: bundle exec rspec spec
