# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2673d37aa96fb53cef5ed602ec39642bcebfac57309f6a55f813ebd636b328f042612d1eac3693aab74907b0c0b7c77794238dce2cef62019b16915d368a3b1d

test:
  secret_key_base: d07c5245266e13685b90882fae5c79d73cb1dd0d050adf0add1d467cd79c29968fb2baecbbd80d6f8244dfe6f9eb500594fa6813e0e82ab3c1c0e85df6c9ed56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
